# Generated by Django 5.0.7 on 2024-08-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wanguser',
            name='emmail',
        ),
        migrations.AddField(
            model_name='wanguser',
            name='email',
            field=models.EmailField(default='string', max_length=32),
        ),
    ]
